server:
  port: 8770


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=Hongkong
    username: root
    password: 123



mybatis:
  mapper-locations: mapper/*.xml
